upstream auth_service {
    server auth-service:3000;
}

server {
    listen 80;

    location /api/auth/ {
        proxy_pass http://auth_service;
        
        # Rate limit Auth requests
        limit_req zone=auth_limit burst=20 nodelay;

        # Pass the original host/domain
        # Example: Host: example.com
        proxy_set_header Host $host;

        # Pass the client's IP address
        # Example: X-Real-IP: 192.168.1.10
        proxy_set_header X-Real-IP $remote_addr;

        # Pass the client/proxy IP chain
        # Example: X-Forwarded-For: 192.168.1.10, 10.0.0.5
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Pass the original request protocol
        # Example: X-Forwarded-Proto: https
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}