export const USER_ROLES = {
    PATIENT: "PATIENT",
    DOCTOR: "DOCTOR",
    HOSPITAL_ADMIN: "HOSPITAL_ADMIN",
    GLOBAL_ADMIN: "GLOBAL_ADMIN",
} as const;

export const USER_STATUS = {
    PENDING: "PENDING",
    ACTIVE: "ACTIVE",
    SUSPENDED: "SUSPENDED",
} as const;