events{}

http {
    server_tokens off;

    client_max_body_size 5m;
    # Limit Auth requests to 10 requests per second per client IP
    # auth_limit:10m → creates a 10 MB shared memory zone for tracking request limits
    limit_req_zone $binary_remote_addr zone=auth_limit:10m rate=10r/s;


    include /etc/nginx/conf.d/*.conf;
}